### ISSUE TITLE
Rust crypto for chacha20poly1305

### ISSUE THREAD

**Issue by ernestas-poskus** [heartsucker/rust-secure-session#11]
Hey @heartsucker 

Thanks for this crate, I want to know your opinion on this before doing actual work. What do you think about using chacha20poly1305 implementation from rust-crypto crate ?

https://github.com/DaGenix/rust-crypto/blob/master/src/chacha20poly1305.rs

**Comment by heartsucker** [comment]
Hey @ernestas-poskus. Slow response. If you look [here](https://github.com/heartsucker/rust-secure-session/blob/f64bbdddb8407978df5168026b8357b153971ab0/src/session.rs#L57-L62), you can see that there's already an implementation of the ChaCha20Poly1305 AEAD. Is that what you meant? Or am I missing something?
